version: '3.8'

services:
  app:
    build: ./
    ports:
      - '3000:3000'
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
